AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  Exclude:
    - 'bin/*'
    - 'pkg/**/*'
    - 'tmp/**/*'

plugins:
  - rubocop-rspec
  - rubocop-performance

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

RSpec:
  Language:
    Expect: expect

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/SpecFilePathFormat:
  CustomTransform:
    IoT: iot
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false
