AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - 'bin/*'
    - 'pkg/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
  SuggestExtensions: false

plugins:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-rake

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'lib/dredger/iot/sensors/*_provider.rb'
    - 'spec/**/*'

RSpec:
  Language:
    Expect: expect

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/SpecFilePathFormat:
  CustomTransform:
    IoT: iot
    I2C: i2c
    GPIO: gpio
    BME280: bme280
    BMP180: bmp180
    DHT22: dht22
    DS18B20: ds18b20
    MCP9808: mcp9808

Metrics/BlockLength:
  Exclude:
    - 'examples/**/*'

Metrics/AbcSize:
  Exclude:
    - 'lib/dredger/iot/sensors/*_provider.rb'
