# frozen_string_literal: true

require_relative 'sensors/base_sensor'
require_relative 'sensors/dht22'
require_relative 'sensors/dht22_provider'
require_relative 'sensors/bme280'
require_relative 'sensors/bme280_provider'
require_relative 'sensors/ds18b20'
require_relative 'sensors/ds18b20_provider'
require_relative 'sensors/bmp180'
require_relative 'sensors/mcp9808'
require_relative 'sensors/sht31'
require_relative 'sensors/sht31_provider'
require_relative 'sensors/bh1750'
require_relative 'sensors/bh1750_provider'
require_relative 'sensors/tsl2561'
require_relative 'sensors/tsl2561_provider'
require_relative 'sensors/ina219'
require_relative 'sensors/ina219_provider'
require_relative 'sensors/adxl345'
require_relative 'sensors/adxl345_provider'
require_relative 'sensors/scd30'
require_relative 'sensors/scd30_provider'
